spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/anketa"
    username: ithersta
    password: postgres
  flyway:
    url: "jdbc:postgresql://localhost:5432/anketa"
    user: ithersta
    password: postgres
oauth:
  yandex:
    client-id: "4ab33cd575a54a2aa3617fddabff8388"
yandex-gpt:
  iam-file: "yandex-iam"
  folder-id: "b1goq8mnc2251i4o0o5l"
secrets:
  jwt-secret-file: "test-jwt-secret"
whitelist:
  emails:
    - "ithersta@yandex.ru"
    - "zimaea2015@yandex.ru"
    - "stansurnina@yandex.ru"
